name: gp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  blur: ^3.1.0
  dartz: ^0.10.1
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^9.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  uuid: ^4.5.1
  file_picker: ^11.0.2
  firebase_core: ^4.8.0
  firebase_messaging: ^16.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/home_screen/
    - assets/logo.png
    - assets/logo2.png
    - assets/reset_password.png
    - assets/Password_changed.png
    - assets/email_verification.png
    - assets/account_verified.png
    - assets/done.png
    - assets/email_sent.png
    - assets/successbook.png
    - assets/approved_balloons.svg
    - assets/inqueue_phone.svg
    - assets/notapproved_clock.svg
  uses-material-design: true
  generate: true